<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <AssemblyName>itoguruma-viewer</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Itoguruma.Core/Itoguruma.Core.csproj" />
  </ItemGroup>
</Project>
