<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><OutputType>Exe</OutputType><AssemblyName>itoguruma</AssemblyName></PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Itoguruma.Core/Itoguruma.Core.csproj" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="8.0.1" />
  </ItemGroup>
</Project>
